### ISSUE TITLE
Scope minitest-retry to system tests

### ISSUE THREAD

**Issue by nflorentin** [y-yagi/minitest-retry#41]
Hi, 

I would like to use minitest-retry only for system tests but I didn't find a way to do it.

I tried the option `exceptions_to_retry: [Capybara::CapybaraError]` but it is not working.

I think it's because the `Capybara::CapybaraError` is catch before it reaches minitest-retry.

I think it does not make lot of sense to use minitest-retry with unit test because a retry won't help to make it pass.

Thanks you in advance for your help!

**Comment by y-yagi** [comment]
This is because `exceptions_to_retry` checks an exception name by the exact match. So in your example, it doesn't work when Capybara raises `Capybara::CapybaraError` only, not working other exceptions like `Capybara::ElementNotFound`.

I added the option to filter to target test classes in v0.2.3. Please update `minitest-retry` to v0.2.3 and try like the following. Thanks.

```ruby 
Minitest::Retry.use!(
  classes_to_retry: ["ApplicationSystemTestCase"]
)

```

**Comment by nflorentin** [comment]
awesome ! It works

Thanks for your reactivity @y-yagi :-)
